server:
  port: 8089

spring:
  application:
    name: public-web-service
  datasource:
    url: jdbc:postgresql://localhost:5432/whocloud
    username: whocloud
    password: whocloud123
    driver-class-name: org.postgresql.Driver

management:
  endpoints:
    web:
      exposure:
        include: health,info
